### ISSUE TITLE
fix contextLoadTest

### ISSUE THREAD

**Issue by isaaaabel** [philippabele/tdd-with-java#19]
failed to load Application Context

**Comment by isaaaabel** [comment]
@philippabele could you help me to fix the error related to loading the application context? 
Unfortunately, I don't understand what the reason for the error message is when I run the ContextLoadTest and how I can fix it.

**Comment by philippabele** [comment]
@isaaaabel could you describe your problem in this issue? I just read your question in this issue and do not see any details about your error message.

**Comment by isaaaabel** [comment]
@philippabele 
Der Anwendungskontext kann nicht geladen werden, weil es Probleme beim Erstellen der Bean "todoRepository" gibt. Die Klasse "Todo" wird scheinbar nicht als verwaltete JPA-Entität erkannt.
[Fehlermeldung_FailedLoadKontext.txt](https://github.com/user-attachments/files/15521257/Fehlermeldung_FailedLoadKontext.txt)

- Die Klasse Todo enthält die Annotation: @Entity
- Die Klasse TodoApplication enthält: @EntityScan(basePackages = {"com.todoapp.model"})
- die Klasse JpaConfig enthält: @EnableJpaRepositories(basePackages = "com.todoapp.repository")

Dadurch sollte ermöglicht werden, dass die Jpa-Repositorys und Entitäten richtig gescannt werden und die Todo-Klasse als Jpa-Entität konfiguriert ist.
